apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dapp
  template:
    metadata:
      labels:
        app: dapp
    spec:
      containers:
      - name: dapp
        image: schadokar/eth-server:1.0.0
        ports:
        - containerPort: 4000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dapp-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

