apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapp
  template:
    metadata:
      labels:
        app: dapp
    spec:
      containers:
        - name: dapp
          image: schadokar/eth-server:1.0.0
          ports:
            - containerPort: 4000
          env:
            - name: GANACHE_HOST
              value: ganache-deployment

---
apiVersion: v1
kind: Service
metadata:
  name: dapp-service
spec:
  selector:
    app: dapp
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: NodePort  # Specify the service type as NodePort

