apiVersion: apps/v1
kind: Deployment
metadata:
  name: ganache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ganache
  template:
    metadata:
      labels:
        app: ganache
    spec:
      containers:
        - name: ganache
          image: schadokar/eth-ganache:1.0.0
          ports:
            - containerPort: 8545

---
apiVersion: v1
kind: Service
metadata:
  name: ganache-service
spec:
  selector:
    app: ganache
  ports:
    - protocol: TCP
      port: 8545
      targetPort: 8545
  type: NodePort  # Specify the service type as NodePort

