apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dapp
  template:
    metadata:
      labels:
        app: dapp
    spec:
      containers:
      - name: dapp
        image: sudojarvis/eth-server:latest
        ports:
        - containerPort: 4000
        resources:
          requests:
            cpu: "500m"  # Set the initial request to 500 milli cores
          limits:
            cpu: "1000m"  # Set the upper limit to 1000 milli cores
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dapp-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Set the target CPU utilization percentage

