apiVersion: apps/v1
kind: Deployment
metadata:
  name: ganache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ganache
  template:
    metadata:
      labels:
        app: ganache
    spec:
      containers:
        - name: ganache
          image: schadokar/eth-ganache:1.0.0
          ports:
            - containerPort: 8545

