# dapp-replicaset.yaml
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dapp-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dapp
  template:
    metadata:
      labels:
        app: dapp
    spec:
      containers:
      - name: dapp
        image: schadokar/eth-server:1.0.0
        ports:
        - containerPort: 4000

